# Generated by Django 5.0 on 2023-12-11 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_duration'),
        ('movies_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='purchased_by',
            field=models.ManyToManyField(related_name='purchased_movies', through='movies_orders.MovieOrder', to=settings.AUTH_USER_MODEL),
        ),
    ]
